[program:edge-ota-agent]
command=/data/src/github.com/imneov/devserver/ota-agent/bin/ota-agent --config /data/src/github.com/imneov/devserver/ota-agent/config.yaml
directory=/data/src/github.com/imneov/devserver/ota-agent
autostart=true
autorestart=true
stderr_logfile=/var/log/edge-ota-agent.err.log
stdout_logfile=/var/log/edge-ota-agent.out.log
