device:
  name: dev-local

mqtt:
  host: 114.119.174.108
  port: 31883
  ca_file: ""

console:
  enabled: true
  port: 9099
  static_dir: ""

kubernetes:
  kubeconfig: /root/.kube/hwneov.config
  namespace: default
  apiserver_url: https://114.119.174.108:30443

logging:
  level: debug
  file: ""
